# Generated by Django 2.0.2 on 2018-02-13 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sightingsapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='species',
            old_name='accepted_species',
            new_name='accepted',
        ),
    ]
