# Generated by Django 2.0.2 on 2018-02-13 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sightingsapp', '0002_auto_20180213_1734'),
    ]

    operations = [
        migrations.RenameField(
            model_name='species',
            old_name='accepted',
            new_name='name',
        ),
    ]
